# rxyhn's aesthetic alacritty
# configuration for alacritty, the GPU enhanced terminal emulator.

colors:
  # night colorschemes
  primary:
    background: '#061115'
    foreground: '#D9D7D6'

  cursor:
    text:   CellForeground
    cursor: '#D9D7D6'
    
  normal:
    black:   '#1C252C'
    red:     '#DF5B61'
    green:   '#78B892'
    yellow:  '#DE8F78'
    blue:    '#6791C9'
    magenta: '#BC83E3'
    cyan:    '#67AFC1'
    white:   '#D9D7D6'

  bright:
    black:   '#484E5B'
    red:     '#F16269'
    green:   '#8CD7AA'
    yellow:  '#E9967E'
    blue:    '#79AAEB'
    magenta: '#C488EC'
    cyan:    '#7ACFE4'
    white:   '#E5E5E5'

env:
  TERM: xterm-256color

window:
  opacity: 1.0
  dynamic_padding: true
  padding:
    x: 25
    y: 25

font:
  normal:
    family: SFMono Nerd Font
    style: Regular

  bold:
    family: SFMono Nerd Font
    style: Bold

  italic:
    family: SFMono Nerd Font
    style: Italic

  bold_italic:
    family: SFMono Nerd Font
    style: Bold Italic

  size: 10

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

selection:
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

shell:
  program: /usr/bin/zsh

cursor:
  style: Underline

live_config_reload: true
draw_bold_text_with_bright_colors: true